import Link from "next/link";
import { fetchFeed, fetchRepoStats } from "@/lib/github";
import { getDispatch, getEnv } from "@/lib/kv";
import { getFacts } from "@/lib/facts";
import { Ticker } from "@/components/ticker";
import { StatGrid } from "@/components/stat-grid";
import { FeedCard } from "@/components/feed-card";
import { Seal } from "@/components/seal";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import type { CuratedDispatch, FeedItem, RepoStats } from "@/lib/types";

export const revalidate = 1800;

const FALLBACK_STATS: RepoStats = {
  stars: 0,
  forks: 0,
  openIssues: 0,
  openPulls: 0,
  contributors: 98,
  fetchedAt: new Date().toISOString(),
};

const FALLBACK_DISPATCH_EN: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "CodeWhale — the terminal coding agent for open models",
  summary:
    "CodeWhale runs in your terminal, talks to DeepSeek V4 and other open-weight models through any provider, and respects your filesystem. The dispatch below is regenerated by DeepSeek V4-Flash on a six-hour cron — you'll see real repo activity here once the cron runs.",
  highlights: [
    { title: "Read the install guide", href: "/install", tag: "shipped", blurb: "npm, Cargo, Homebrew, direct download — pick your path." },
    { title: "Browse open issues", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "Triaged on GitHub — start with anything labelled 'good first issue'." },
    { title: "Review the roadmap", href: "/roadmap", tag: "discussion", blurb: "What's confirmed, what's being weighed, what's been ruled out." },
  ],
  movers: [],
};

const FALLBACK_DISPATCH_ZH: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "CodeWhale — 面向开源模型的终端编程智能体",
  summary:
    "CodeWhale 运行在你的终端中，接入 DeepSeek V4 等开源模型，对文件系统保持克制。以下「今日要闻」由 DeepSeek V4-Flash 每六小时自动生成——仓库有动态时会实时更新。",
  highlights: [
    { title: "阅读安装指南", href: "/zh/install", tag: "shipped", blurb: "npm、Cargo、Homebrew、直接下载——任选其一。" },
    { title: "浏览开放议题", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "在 GitHub 上查看——从标记为 good first issue 的议题开始。" },
    { title: "查看路线图", href: "/zh/roadmap", tag: "discussion", blurb: "已确认、审议中、以及已排除的功能规划。" },
  ],
  movers: [],
};

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  const env = await getEnv();
  const facts = await getFacts();

  let stats: RepoStats = FALLBACK_STATS;
  let feed: FeedItem[] = [];
  let dispatch: CuratedDispatch = isZh ? FALLBACK_DISPATCH_ZH : FALLBACK_DISPATCH_EN;

  try {
    [stats, feed] = await Promise.all([
      fetchRepoStats(env.GITHUB_TOKEN),
      fetchFeed(env.GITHUB_TOKEN, 12),
    ]);
  } catch (e) {
    console.error("github fetch failed", e);
  }

  try {
    const cached = await getDispatch();
    if (cached) dispatch = cached;
  } catch {
    /* keep fallback */
  }

  return (
    <>
      <Ticker items={feed} />

      {/* HERO */}
      <section className="relative overflow-hidden">
        <div className="margin-glyph right-[-2rem] top-[2rem] hidden lg:block">深</div>

        <div className="mx-auto max-w-[1400px] px-4 sm:px-6 pt-10 sm:pt-14 pb-12 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-8">
            <div className="flex items-center gap-2 sm:gap-3 mb-6 flex-wrap">
              <span className="pill pill-hot">DeepSeek V4 · 1M context</span>
              <span className="pill pill-jade">OpenRouter</span>
              <span className="pill pill-ghost">MIT licensed</span>
            </div>

            <h1 className="font-display tracking-crisp">
              {isZh
                ? "开源模型的终端编程智能体。"
                : "The terminal coding agent for open models."}
            </h1>

            <p className="mt-6 text-lg text-ink-soft leading-relaxed max-w-2xl">
              <span className="font-cjk text-indigo font-semibold">CodeWhale</span>
              {isZh
                ? " 是一个终端原生的编程智能体，面向 DeepSeek V4 及其他开源／开放权重模型。它编辑文件、执行 Shell、调用 MCP 服务器、协调子智能体——并在你的文件系统沙箱内运行。DeepSeek API 直连、OpenRouter、Hugging Face 推理端点、自托管——任选你的接入方式。"
                : " is a terminal-native coding agent for DeepSeek V4 and other open / open-weight models. It edits files, runs shells, calls MCP servers, coordinates sub-agents — and runs inside your filesystem sandbox. Native DeepSeek API, OpenRouter, Hugging Face inference, self-hosted — bring your own provider."}
            </p>

            <div className="mt-8 flex flex-wrap items-stretch sm:items-center gap-3">
              <Link
                href={isZh ? "/zh/install" : "/install"}
                className="flex-1 sm:flex-none text-center px-5 py-3 bg-ink text-paper font-mono text-sm uppercase tracking-wider hover:bg-indigo transition-colors"
              >
                {isZh ? "立即安装 →" : "Install →"}
              </Link>
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="flex-1 sm:flex-none text-center px-5 py-3 hairline-t hairline-b hairline-l hairline-r font-mono text-sm uppercase tracking-wider hover:bg-paper-deep transition-colors"
              >
                ★ GitHub
              </Link>
              <Link
                href={isZh ? "/zh/docs" : "/docs"}
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
              >
                {isZh ? "阅读文档" : "Docs"}
              </Link>
              <Link
                href="/roadmap"
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
              >
                {isZh ? "路线图" : "Roadmap"}
              </Link>
            </div>

            {/* Trust signals */}
            <div className="mt-6 flex items-center gap-4 text-xs font-mono text-ink-mute flex-wrap">
              <span>{isZh ? "独立维护者 Hmbown" : "Maintained by Hmbown"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.version ?? "v0.8.x"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.providers.length} providers</span>
            </div>
          </div>

          {/* hero side: install card */}
          <div className="lg:col-span-4">
            <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-5 relative">
              <div className="absolute -top-3 left-4 bg-paper px-2 eyebrow">
                {isZh ? "开始使用 · 一行安装" : "get started · 开始使用"}
              </div>
              <pre className="code-block mt-2">
                {isZh ? (
                  <>
                    <span className="comment"># npm 安装（推荐，无需 Rust 工具链）</span>{"\n"}
                    <span className="prompt">$</span> npm install -g codewhale{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># 或 Cargo 安装</span>{"\n"}
                    <span className="prompt">$</span> cargo install codewhale-cli --locked{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># 已安装？更新到最新版</span>{"\n"}
                    <span className="prompt">$</span> codewhale update{"\n"}
                    <br />
                    <span className="comment"># 首次运行自动创建 <span className="key">~/.deepseek/</span></span>
                  </>
                ) : (
                  <>
                    <span className="comment"># npm install (recommended, no Rust toolchain)</span>{"\n"}
                    <span className="prompt">$</span> npm install -g codewhale{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># or Cargo install</span>{"\n"}
                    <span className="prompt">$</span> cargo install codewhale-cli --locked{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># already installed? pull the latest</span>{"\n"}
                    <span className="prompt">$</span> codewhale update{"\n"}
                    <br />
                    <span className="comment"># first run sets up <span className="key">~/.deepseek/</span></span>
                  </>
                )}
              </pre>
              <div className="mt-3 flex items-center justify-between text-[0.7rem] font-mono text-ink-mute">
                <span>{isZh ? "需要 Node 或 Rust 1.88+" : "needs Node or Rust 1.88+"}</span>
                <Link href={isZh ? "/zh/install" : "/install"} className="text-indigo hover:underline">{isZh ? "其他方式 →" : "other ways →"}</Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <StatGrid stats={stats} />

      {/* TODAY'S DISPATCH */}
      <section className="mx-auto max-w-[1400px] px-6 py-16">
        <div className="flex items-end justify-between mb-6 hairline-b pb-4">
          <div>
            <div className="eyebrow mb-2">{isZh ? "今日要闻" : "Today's Dispatch · 今日要闻"}</div>
            <h2 className="font-display tabular text-ink-mute font-mono text-base">
              {new Date(dispatch.generatedAt).toISOString().slice(0, 10)}
            </h2>
          </div>
          <div className="text-right">
            <div className="eyebrow">{isZh ? "由 … 编辑" : "Curated by"}</div>
            <div className="font-mono text-sm">DeepSeek V4-Flash · 6h cron</div>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-10">
          {/* editorial */}
          <div className="lg:col-span-7">
            <article className="space-y-5">
              <h3 className="font-display text-3xl leading-tight">
                {isZh && dispatch.headlineZh ? dispatch.headlineZh : dispatch.headline}
              </h3>
              <p className={isZh ? "text-ink-soft leading-[1.9] tracking-wide text-[1.02rem]" : "text-ink-soft leading-relaxed text-[1.02rem]"}>
                {isZh && dispatch.summaryZh ? dispatch.summaryZh : dispatch.summary}
              </p>

              <div className="hairline-t pt-5">
                <div className="eyebrow mb-3">{isZh ? "要点" : "Highlights · 要点"}</div>
                <ul className="divide-y divide-paper-line/40 hairline-t hairline-b">
                  {(isZh && dispatch.highlightsZh ? dispatch.highlightsZh : dispatch.highlights).map((h, i) => (
                    <li key={i} className="py-3 flex items-start gap-4">
                      <span className="font-mono text-[0.7rem] text-indigo uppercase tracking-widest pt-1 w-20 shrink-0">
                        {h.tag}
                      </span>
                      <div className="flex-1">
                        <Link href={h.href} className="body-link font-display text-lg leading-snug">
                          {h.title}
                        </Link>
                        <p className={`text-sm text-ink-soft mt-1 ${isZh ? "leading-[1.8]" : ""}`}>{h.blurb}</p>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>

              {(isZh && dispatch.moversZh ? dispatch.moversZh : dispatch.movers).length > 0 && (
                <div className="pt-2">
                  <div className="eyebrow mb-3">{isZh ? "进展" : "Movers · 进展"}</div>
                  <ul className="space-y-2">
                    {(isZh && dispatch.moversZh ? dispatch.moversZh : dispatch.movers).map((m) => (
                      <li key={m.number} className="flex items-baseline gap-3 text-sm">
                        <span className="font-mono text-indigo tabular">#{m.number}</span>
                        <Link href={m.href} className="font-medium hover:text-indigo">{m.title}</Link>
                        <span className="text-ink-mute">— {m.reason}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </article>
          </div>

          {/* recent activity column */}
          <aside className="lg:col-span-5">
            <div className="hairline-t hairline-b hairline-l hairline-r bg-paper">
              <div className="bg-ink text-paper px-4 py-2 flex items-center justify-between">
                <div className="font-cjk text-sm tracking-wider">{isZh ? "最新活动" : "最新活动 · Recent activity"}</div>
                <Link href={isZh ? "/zh/feed" : "/feed"} className="font-mono text-[0.7rem] uppercase tracking-wider hover:text-indigo">
                  {isZh ? "全部 →" : "All →"}
                </Link>
              </div>
              <div className="px-4">
                {feed.slice(0, 5).map((item) => (
                  <FeedCard key={item.url} item={item} />
                ))}
                {feed.length === 0 && (
                  <div className="py-8 text-center text-sm text-ink-mute font-mono">
                    {isZh ? "暂无数据 · feed not loaded" : "feed not yet loaded · 暂无数据"}
                  </div>
                )}
              </div>
            </div>
          </aside>
        </div>
      </section>

      {/* WHAT IT IS */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-16">
          <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
            <Seal char="是" />
            <h2 className="font-display">
              {isZh ? "它到底是什么" : "What it actually is"}
            </h2>
          </div>

          <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
            {isZh ? (
              <>
                <div className="p-6">
                  <div className="eyebrow mb-3">01 · 终端智能体</div>
                  <h3 className="font-display text-xl mb-3">编程智能体，不是聊天框</h3>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    与 Claude Code、Codex CLI 相同的循环。读、改、跑测试、汇报。键盘驱动，住在你的终端里。
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">02 · 开源模型优先</div>
                  <h3 className="font-display text-xl mb-3">DeepSeek V4 深度集成</h3>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    DeepSeek 原生 API 为一级路径：推理块流式传输、缓存指标、思考力度选择。同时支持 OpenRouter、Hugging Face、自托管——任你选择。
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">03 · 沙箱边界</div>
                  <h3 className="font-display text-xl mb-3">Plan、Agent、YOLO</h3>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    Plan 只读调查，Agent 按需审批，YOLO 自动批准。沙箱：seatbelt (macOS)、landlock (Linux)；Windows 受限令牌。
                  </p>
                </div>
              </>
            ) : (
              <>
                <div className="p-6">
                  <div className="eyebrow mb-3">01 · 终端智能体</div>
                  <h3 className="font-display text-xl mb-3">A coding agent, not a chat box</h3>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    Same loop as Claude Code or Codex CLI. Reads, edits, runs tests, reports back. Keyboard-driven, lives in your terminal.
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">02 · 开源模型优先</div>
                  <h3 className="font-display text-xl mb-3">DeepSeek V4, deeply integrated</h3>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    Native DeepSeek API is the first-class path: reasoning streaming, cache metrics, thinking effort control. OpenRouter, Hugging Face, self-hosted — your call.
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">03 · 沙箱保护</div>
                  <h3 className="font-display text-xl mb-3">Plan, Agent, YOLO</h3>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    Plan reads only. Agent asks for approval on risky ops. YOLO auto-approves. Sandboxed via seatbelt (macOS), landlock (Linux); Windows restricted tokens.
                  </p>
                </div>
              </>
            )}
          </div>

          {/* Provider quick list */}
          <div className="mt-8 hairline-t pt-6">
            <div className="eyebrow mb-4">{isZh ? "内建提供商" : "Built-in providers"}</div>
            <div className="flex flex-wrap gap-2">
              {facts.providers.map((p) => (
                <span key={p.id} className="font-mono text-xs px-2 py-1 hairline-t hairline-b hairline-l hairline-r text-ink-soft">
                  {p.label}
                </span>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="mx-auto max-w-[1400px] px-6 py-16">
        <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
          <Seal char="作" />
          <h2 className="font-display">
            {isZh ? "运作方式" : "How it works"}
          </h2>
        </div>

        <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-4 sm:p-8">
          <MermaidDiagram
            label={isZh ? "CodeWhale 运作方式示意图" : "CodeWhale architecture diagram"}
            chart={
              isZh
                ? `flowchart TD
    A["用户输入<br/>(TUI · ratatui)"] -->|Op channel| B["Engine<br/>turn loop + tools"]
    B -->|HTTPS / SSE| C["DeepSeek API<br/>V4 family"]
    C -->|stream events| B
    B -->|tool call| T["read_file · edit_file · grep<br/>apply_patch · exec_shell<br/>mcp_&lt;server&gt;_&lt;tool&gt;"]
    T -->|approval Y/N| P["审批对话框<br/>approval dialog"]
    P --> B
    T -->|exec| S["沙箱<br/>seatbelt · landlock · win32"]
    classDef accent fill:#e9eefe,stroke:#0e0e10,stroke-width:1px;
    classDef api fill:#0e0e10,stroke:#0e0e10,color:#ffffff;
    class C api;
    class T,P,S accent;`
                : `flowchart TD
    A["You type<br/>(TUI · ratatui)"] -->|Op channel| B["Engine<br/>turn loop + tools"]
    B -->|HTTPS / SSE| C["DeepSeek API<br/>V4 family"]
    C -->|stream events| B
    B -->|tool call| T["read_file · edit_file · grep<br/>apply_patch · exec_shell<br/>mcp_&lt;server&gt;_&lt;tool&gt;"]
    T -->|approval Y/N| P["Approval<br/>dialog"]
    P --> B
    T -->|exec| S["Sandbox<br/>seatbelt · landlock · win32"]
    classDef accent fill:#e9eefe,stroke:#0e0e10,stroke-width:1px;
    classDef api fill:#0e0e10,stroke:#0e0e10,color:#ffffff;
    class C api;
    class T,P,S accent;`
            }
          />
        </div>

        <p className="mt-3 text-xs font-mono text-ink-mute">
          {isZh
            ? "示意图使用 Mermaid 标准格式渲染。"
            : "Rendered with Mermaid standard syntax."}
        </p>
      </section>

      {/* OPEN MODEL PLATFORM */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-16">
          <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
            <Seal char="开" />
            <h2 className="font-display">
              {isZh ? "开放模型平台" : "Open model platform"}
            </h2>
          </div>

          <p className="text-ink-soft max-w-3xl mb-8 leading-relaxed">
            {isZh
              ? "CodeWhale 为 DeepSeek V4 构建了深度的一级集成——推理流、缓存指标、思考力度控制。同时，OpenRouter 已作为二级提供商就绪；Hugging Face 推理端点、自托管 OpenAI 兼容端点、本地模型服务也在规划中。目标明确：CodeWhale 应成为所有开放／开源编码模型的终端智能体。"
              : "CodeWhale ships with deep first-class integration for DeepSeek V4 — reasoning streams, cache metrics, thinking effort control. OpenRouter is ready as a secondary provider. Hugging Face inference endpoints, self-hosted OpenAI-compatible endpoints, and local model serving are on the roadmap. The direction is clear: CodeWhale should be THE terminal agent for all open / open-weight coding models."}
          </p>

          <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
            {isZh ? (
              <>
                <div className="p-6">
                  <div className="font-display text-xl mb-2 text-indigo">DeepSeek · 一级</div>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    原生 DeepSeek API 直连。推理内容流式传输、缓存命中指标、模型自动路由（Fin）。DeepSeek 不会被弃用。
                  </p>
                </div>
                <div className="p-6">
                  <div className="font-display text-xl mb-2 text-indigo">OpenRouter · 就绪</div>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    通过 OpenRouter 接入 DeepSeek 模型及更多。统一 API 层，按使用量计费。设置 OPENROUTER_API_KEY 即可。
                  </p>
                </div>
                <div className="p-6">
                  <div className="font-display text-xl mb-2 text-indigo">更多 · 规划中</div>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    Hugging Face 推理端点、自托管（vLLM / sglang / Ollama）、Unsloth 微调适配——这些是平台路线图的一部分，尚未完全实现。
                  </p>
                </div>
              </>
            ) : (
              <>
                <div className="p-6">
                  <div className="font-display text-xl mb-2 text-indigo">DeepSeek · first-class</div>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    Native DeepSeek API direct. Reasoning streaming, cache hit metrics, model auto-routing (Fin). DeepSeek is not deprecated.
                  </p>
                </div>
                <div className="p-6">
                  <div className="font-display text-xl mb-2 text-indigo">OpenRouter · ready</div>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    Access DeepSeek models and more through OpenRouter. Unified API layer, usage-based billing. Set OPENROUTER_API_KEY and go.
                  </p>
                </div>
                <div className="p-6">
                  <div className="font-display text-xl mb-2 text-indigo">More · planned</div>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    Hugging Face inference, self-hosted (vLLM / sglang / Ollama), Unsloth fine-tune adapters — on the platform roadmap, not fully implemented yet.
                  </p>
                </div>
              </>
            )}
          </div>

          <div className="mt-8 hairline-t pt-6 flex items-center gap-4">
            <Link href="/roadmap" className="font-mono text-sm uppercase tracking-wider text-indigo hover:underline">
              {isZh ? "查看完整路线图 →" : "Full roadmap →"}
            </Link>
            <Link href="/docs" className="font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors">
              {isZh ? "提供商配置文档 →" : "Provider config docs →"}
            </Link>
          </div>
        </div>
      </section>

      {/* JOIN IN */}
      <section className="bg-ink text-paper">
        <div className="mx-auto max-w-[1400px] px-6 py-16 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-5">
            <div className="eyebrow text-paper-deep/70 mb-3">{isZh ? "加入" : "Join in"}</div>
            <h2 className="font-display text-paper text-4xl leading-tight">
              {isZh ? "这是一个小项目。你的每个补丁都很重要。" : "This is a small project. Your patch matters."}
            </h2>
            <p className={`mt-5 text-paper-deep/80 ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "无 CLA，无赞助商锁定。维护者亲自阅读每一条内容。议题在公开环境下分类。版本从 main 分支发布。"
                : "No CLA. No sponsor lockouts. The maintainer reads everything personally. Issues triaged in the open. Releases cut from main."}
            </p>
            <div className="mt-6 flex items-center gap-3">
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="px-4 py-2 hairline-t hairline-b hairline-l hairline-r border-white/20 text-paper font-mono text-sm hover:bg-white/10 transition-colors"
              >
                ★ Star on GitHub
              </Link>
              <Link
                href="/contribute"
                className="px-4 py-2 font-mono text-sm text-paper-deep/80 hover:text-paper transition-colors"
              >
                {isZh ? "参与贡献 →" : "Contribute →"}
              </Link>
            </div>
          </div>

          <div className="lg:col-span-7 grid sm:grid-cols-3 gap-px bg-paper/15">
            {(isZh
              ? [
                  { t: "34k+", d: "星标" },
                  { t: "98+", d: "贡献者" },
                  { t: `${facts.providers.length}+`, d: "提供商" },
                ]
              : [
                  { t: "34k+", d: "Stars" },
                  { t: "98+", d: "Contributors" },
                  { t: `${facts.providers.length}+`, d: "Providers" },
                ]
            ).map((s) => (
              <div key={s.d} className="bg-ink p-6 text-center">
                <div className="font-display text-4xl mb-1 text-jade">{s.t}</div>
                <div className="font-cjk text-sm text-paper-deep/70">{s.d}</div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
